Completed regex matching Added a logging system Purge instance will purge and re-install project packages installed as well. Fix to bugs Works very well here.

diff --git a/hooks/install b/hooks/install
--- a/hooks/install
+++ b/hooks/install
@@ -22,14 +22,22 @@ package_directory=`config-get rainbow-installation-directory`
 package_directory="$(echo $package_directory | sed 's/\(.*\)\/$/\1/g')"
 
 
-
 if ! [ -e "$package_directory" ]; then
-       if ( ! mkdir -p $package_directory 2> /dev/null ); then
+       if ( ! mkdir -p $package_directory 2>> $log_file_rev ); then
           # Not gonna allow bad package installation directory
             package_directory="/var/lib/django-rainbow"
             mkdir -p $package_directory
        fi
 fi
+
+log_file_rev="$package_directory/install_revision_$(cat revision).log"
+
+
+# Create the directory for charm logging
+if ! [ -e "$package_directory/logs" ]; then
+       mkdir $package_directory/logs
+fi
+
 
 # Create the directory for addition packages via pip, git, or bzip
 if ! [ -e "$package_directory/packages" ]; then
@@ -50,6 +58,9 @@ fi
 
 # Erase data if exists and poplulate the temp file for listed packages
 echo "" > $package_directory/temp_installed
+for pkg in $(echo "$native_packages"); do
+    echo "$pkg" >> $package_directory/temp_installed
+done;
 for pkg in $(echo "$additional_debian_packages"); do
     echo "$pkg" >> $package_directory/temp_installed
 done;
@@ -74,14 +85,17 @@ if [ -n "$purge_instance" ]; then
      juju-log "REMOVING $native_packages via apt-get"
      apt-get -y purge $native_packages
 
-     # This will remove all Django and python packages from the python directory
+     # This will remove Django and python packages from the python directory
+     ( ! rm -r /usr/local/lib/python2.7/dist-packages/ 2>> $log_file_rev ) && juju-log "Could not remove python packages at /usr/local/lib/python2.7/dist-packages/" 
+     # Delete the packages directory sense we removed all of the dist-packages
+     ( ! rm -r $package_directory/packages/* 2>> $log_file_rev ) && juju-log "Could not remove python packages at $package_directory/packages/" 
 
-     ( ! rm -r /usr/local/lib/python2.7/dist-packages/ 2> /dev/null ) && juju-log "Could not clean python packages at /usr/local/lib/python2.7/dist-packages/" 
 fi # Endo if [ -n "$purge_instance" ]; then
 
 # Add all packages to the installed file for next run re-installation
 
-new_list="$(comm -13 <(sort $package_directory/installed) <(sort $package_directory/temp_installed))"
+# new_list="$(comm -13 <(sort $package_directory/installed) <(sort $package_directory/temp_installed))"
+# Overwrite the installed file with cp
 cp $package_directory/temp_installed $package_directory/installed
 
 # Installed file now contains all additional packages to be installed now and removed next time this happens
@@ -95,6 +109,8 @@ cp $package_directory/temp_installed $package_directory/installed
           apt-get -qqy install $additional_debian_packages
      fi
 
+cd $package_directory/packages
+
 
 juju-log "Installing bzr packages"
 for bzr_repo in $bzr_repo_packages; do
@@ -104,9 +120,9 @@ bzr_repo_name="$(echo $bzr_repo | sed 's/.*lp:\(.*\)/\1/g' | sed 's/\ //g')"
 
 mkdir $bzr_repo_name
 cd $bzr_repo_name
-( ! bzr branch $bzr_repo 2> /dev/null ) && juju-log "Unable to branch bzr repository $bzr_repo"
+( ! bzr branch $bzr_repo 2>> $log_file_rev ) && juju-log "Unable to branch bzr repository $bzr_repo"
 cd "$(find . -name 'setup.py' | sed 's/setup\.py//g')"
-( ! python setup.py install 2> /dev/null ) && juju-log "Could install bzr package $bzr_repo_name while running python setup.py install"
+( ! python setup.py install 2>> $log_file_rev ) && juju-log "Could install bzr package $bzr_repo_name while running python setup.py install"
 cd $package_directory/packages
 done;
 
@@ -120,9 +136,9 @@ git_repo_name="$(echo $git_repo | sed 's/.*\/\(.*\)\.git/\1/g' | sed 's/\ //g')"
 
 mkdir $git_repo_name
 cd $git_repo_name
-( ! git clone $git_repo 2> /dev/null ) && juju-log "Unable to git clone repository $git_repo"
+( ! git clone $git_repo 2>> $log_file_rev ) && juju-log "Unable to git clone repository $git_repo"
 cd "$(find . -name 'setup.py' | sed 's/setup\.py//g')"
-( ! python setup.py install 2> /dev/null ) && juju-log "Could install git package $git_repo_name while running python setup.py install"
+( ! python setup.py install 2>> $log_file_rev ) && juju-log "Could install git package $git_repo_name while running python setup.py install"
 cd $package_directory/packages
 done;
 
@@ -137,17 +153,13 @@ bzip_repo_name="$(echo $bzip_repo | sed 's/.*\/\(.*\)\.tar\.gz/\1/g' | sed 's/\ 
 mkdir $bzip_repo_name
 cd $bzip_repo_name
 
-( ! wget $bzip_repo 2> /dev/null ) && juju-log "Unable to retrieve tar.gz file $git_repo"
-( ! tar xfv * 2> /dev/null ) && juju-log "Unable to extract file $git_repo" 
+( ! wget $bzip_repo 2>> $log_file_rev ) && juju-log "Unable to retrieve tar.gz file $git_repo"
+( ! tar xfv * 2>> $log_file_rev ) && juju-log "Unable to extract file $git_repo" 
 
 cd "$(find . -name 'setup.py' | sed 's/setup\.py//g')"
-( ! python setup.py install 2> /dev/null ) && juju-log "Could install bzip package $bzip_repo_name while running python setup.py install"
+( ! python setup.py install 2>> $log_file_rev ) && juju-log "Could install bzip package $bzip_repo_name while running python setup.py install"
 cd $package_directory/packages
 done;
-
-
-
-
 
 cd $package_directory/packages
 
@@ -158,9 +170,8 @@ if ! [ -e "Django-1.4" ]; then
 fi
 
 
-
 juju-log "Checking for package mysql-server..."
-if ( dpkg -s mysql-server | grep installed 2> /dev/null ); then
+if ( dpkg -s mysql-server | grep installed 2>> $log_file_rev ); then
      juju-log "...installed"
      package="installed"
 else
