Update to many things here. Fixed the instalation hook to be more freindly and tolerable. Update to the readme. Added a option to reinstall mysql at user request. Database credentials makes sence now and is working. MUCH HARDER TO BREAK BY PLAYING WITH IT!

diff --git a/hooks/rainbow-relation-changed b/hooks/rainbow-relation-changed
--- a/hooks/rainbow-relation-changed
+++ b/hooks/rainbow-relation-changed
@@ -10,10 +10,26 @@ app_url=`relation-get app_source_url`
 app_uname=`relation-get app_source_uname`
 app_pass=`relation-get app_source_pass`
 app_vhost=`relation-get app_source_vhost`
+stripe_additional_debian_packages=`relation-get stripe_additional_debian_packages`
+stripe_additional_pip_packages=`relation-get stripe_additional_pip_packages`
 
-# Need these. Exit until I get them from the stripe. Juju automatically does this.
+
+# Need these. Exit until I get them from the stripe. Juju automatically does this
+# intill they are non-empty
 if [ -z "$app_type" ]; then
      exit 0;
+fi
+
+
+# Install these if the user defined any in the stripe config.yaml file
+if [ "$stripe_additional_debian_packages" ]; then
+    juju-log "Installing extra debian packages: $stripe_additional_debian_packages"
+    sudo apt-get -y install $stripe_additional_debian_packages
+fi
+
+if [ "$stripe_additional_pip_packages" ]; then
+    juju-log "Installing extra pip packages: $stripe_additional_pip_packages"
+    sudo pip install $stripe_additional_pip_packages
 fi
 
 
@@ -88,6 +104,7 @@ else
      hg update
 fi # Endo if [ -z "$repo_dir" ]; then
 
+
 # Store the name of the directory which conatins the settings.py file
 # as the project name
 app_source_package_name="$(find . -iname 'settings.py' | sed 's/.*\/\(.*\)\/settings.py/\1/g')"
@@ -118,37 +135,49 @@ if [ "$database_engine" != "mysql" ]; then
 fi
 
 if [ -z "$database_host" ]; then
-       database_host=`unit-get private-address`
+     database_host="localhost"
+#       database_host=`unit-get private-address`
 fi
+
+open-port 80/tcp
+
+cp /var/django_rainbow/vhost_temp /etc/apache2/sites-available/vhost_$app_source_package_name
 
 # Get the mysql password that was generated by the install hook
 password=`cat /var/lib/juju/mysql.passwd`
 
+chown -R www-data "$repo_dir"
 cd $app_source_directory
-chown -R www-data *
 
 # Determine if a database needs to be created for this service
 existing_databases=`mysql --user="root" --password="$password" --silent --execute 'show databases'`
+
 for db in $existing_databases; do
     if [ "$db" = "$database_name" ]; then
         juju-log "Database already exists, publishing details and exiting"
-        python manage.py syncdb 
-        exit 0 # database already exists
+        if ( ! python manage.py syncdb 2> /dev/null ); then
+             juju-log "Unable to sync database $database_name with project. Re-issuing credentials."
+             echo "grant all on $database_name.* to '$database_user'@'$database_host' identified by '$database_pass'" | mysql --password="$password" --database="$database_name"
+             if ( ! python manage.py syncdb ); then
+                  juju-log "Unable to set username and password from Django project. Quitting."
+                  exit 9;
+             fi
+        fi
+        a2ensite vhost_$app_source_package_name
+        apache2ctl -k graceful
+        # All done, no need to create the database below.
+        exit 0; 
     fi
 done
 
 # Create new database and corresponding security settings for stripe
 juju-log "Creating new database and corresponding security settings"
 mysqladmin --password="$password" create "$database_name"
-echo "grant all on $database_name.* to $database_user identified by '$database_pass'" | mysql --password="$password" --database="$database_name"
+echo "grant all on $database_name.* to '$database_user'@'$database_host' identified by '$database_pass'" | mysql --password="$password" --database="$database_name"
 
 # Change this so it can support removing databases and users with config options -->
 #mysqladmin --password="$password" flush-privileges
-
 python manage.py syncdb 
-open-port 80/tcp
-
-cp /var/django_rainbow/vhost_temp /etc/apache2/sites-available/vhost_$app_source_package_name
 a2ensite vhost_$app_source_package_name
 apache2ctl -k graceful
 
